services:
  inspector:
    image: mcp/inspector:latest
    container_name: inspector
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - inspector
networks:
  inspector:
    driver: bridge