cluster:
  name: "performance-elasticsearch"
  initial_master_nodes: "192.168.8.221:9300,192.168.8.221:9301"
  routing:
    allocation:
      disk:
        watermark:
          low: "20gb"
          high: "15gb"
          flood_stage: "10gb"
node:
  name: "slave"
network:
  bind_host: 0.0.0.0
  publish_host: 192.168.8.221
http:
  port: 9201
  cors:
    enabled: true
    allow-origin: "*"
transport:
  port: 9301
discovery:
  seed_hosts: "192.168.8.221:9300"
bootstrap:
  memory_lock: true
xpack:
  security:
    enabled: false