type: S3
config:
  bucket: thanos
  endpoint: 192.168.8.146:19000
  access_key: minio
  insecure: true
  signature_version2: false
  secret_key: miniostorage
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 1m30s
    response_header_timeout: 2m
    insecure_skip_verify: false
    tls_handshake_timeout: 10s
    expect_continue_timeout: 1s
    max_idle_conns: 100
    max_idle_conns_per_host: 100
    max_conns_per_host: 0